FROM node:18-bullseye

WORKDIR /app

# Install Python and PostgreSQL dependencies
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    python3-venv \
    libpq-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install Nodemon globally
RUN npm install -g nodemon

# Install Node dependencies
COPY package.json package-lock.json ./
RUN npm install

# Copy all files
COPY . .

RUN pip3 install --no-cache-dir -r scripts/requirements.txt

# Generate Prisma Client
RUN npx prisma generate

# Install Nodemon globally
RUN npm install -g nodemon

EXPOSE 5001

# Use environment to decide the command
CMD ["sh", "-c", "npm run migrate && npm run ${NODE_ENV:-dev}"]
