# Use official Node.js image
FROM node:18
RUN apt-get update

# Set working directory
WORKDIR /app

# Copy frontend files
COPY package*.json ./
RUN npm install

# Copy all frontend source files
COPY . .

# Set environment variable for Vite
ARG VITE_APP_BASE_URL
ENV VITE_APP_BASE_URL=$VITE_APP_BASE_URL

# Build the React app
RUN npm run build

# Serve the frontend using a simple server
RUN npm install -g serve
EXPOSE 3000
CMD ["serve", "-s", "dist", "-l", "3000"]